_BASE_: "Base-DiffusionDet.yaml"

MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  # RESNETS:
  #   DEPTH: 50
  #   STRIDE_IN_1X1: False
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"  # 使用Swin Transformer的预训练权重
  BACKBONE:
    NAME: "build_swintransformer_fpn_backbone"  # 使用Swin Transformer作为主干网络
  SWIN:
    SIZE: B-22k
  DiffusionDet:
    NUM_PROPOSALS: 200
    NUM_CLASSES: 10
    HeatMap_WEIGHT: 1.5
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3"]  # 使用Swin Transformer的特征图名称
  ROI_HEADS:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
DATASETS:
  TRAIN: ("props_train",)
  TEST: ("props_val",)

INPUT:
  MIN_SIZE_TRAIN: (480,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 640
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (480, 640)
  FORMAT: "RGB"

SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.0001
  STEPS: (7000, 12000)  # 在10000和15000次迭代时降低学习率
  MAX_ITER: 15000  # 减少总迭代次数以适应PROPS数据集
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  BACKBONE_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 4000
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"  # 使用WarmupMultiStepLR调度器
  GAMMA: 0.1  # 学习率衰减因子

# OUTPUT_DIR: "output/props_res50"
OUTPUT_DIR: "output/props_heat_128"
VIS_DIR: "output/visualization"

# 添加TensorBoard配置
TEST:
  EVAL_PERIOD: 1000  # 每1000次迭代评估一次
