_BASE_: "Base-DiffusionDet.yaml"

MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  # RESNETS:
  #   DEPTH: 50
  #   STRIDE_IN_1X1: False
  WEIGHTS: "models/swin_base_patch4_window7_224_22k.pkl"  # use swin transformer pretrained weights
  BACKBONE:
    NAME: "build_swintransformer_fpn_backbone"  # Backbone network
  SWIN:
    SIZE: B-22k
  DiffusionDet:
    NUM_PROPOSALS: 200     # Number of random proposals to generate for each image
    NUM_CLASSES: 10           # PROPS has 10 classes
    HeatMap_WEIGHT: 1.5         # Weight for the heatmap loss
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3"]  
  ROI_HEADS:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
DATASETS:
  TRAIN: ("props_train",)
  TEST: ("props_val",)

INPUT:
  MIN_SIZE_TRAIN: (480,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 640
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (480, 640)
  FORMAT: "RGB"

SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.0001
  STEPS: (7000, 12000)  # decrease learning rate at 7000 and 12000 iterations
  MAX_ITER: 15000  
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  BACKBONE_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 4000
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"  
  GAMMA: 0.1  

# OUTPUT_DIR: "output/props_res50"
#OUTPUT_DIR: "output/props_heat_128"
OUTPUT_DIR: "output"
VIS_DIR: "output/visualization"

TEST:
  EVAL_PERIOD: 1000  # evaluate at each 1000 iterations
